baseURL = "https://805bluebell.github.io/secondDashDocs/"
# baseURL = "/"

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Talent Aquisition Reports - Docs"
theme = "hugo-theme-techdoc"

hasCJKLanguage = true
metaDataFormat = "yaml"

pygmentsCodeFences = true
pygmentsUseClasses = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

publishDir = "docs"

[Params]

    # Souce Code repository section
    description = "Deciphered"
    github_repository = "https://github.com/805bluebell/secondDash"
    version = "0.0.1"

    # Documentation repository section
    # documentation repository (set edit link to documentation repository)
    github_doc_repository = "https://github.com/thingsym/hugo-theme-techdoc"

    # Analytic section
    google_analytics_id = "" # Your Google Analytics tracking id
    tag_manager_container_id = "" # Your Google Tag Manager container id
    google_site_verification = "" # Your Google Site Verification for Search Console

    # Open Graph and Twitter Cards settings section
    title = "Hugo Techdoc Theme"
    images = ["og-image.png"]
    # See https://gohugo.io/templates/internal/#open-graph
    # See https://gohugo.io/templates/internal/#twitter-cards

    # Theme settings section
    # Theme color
    custom_font_color = ""
    custom_background_color = ""

    # Documentation Menu section
    # Menu style settings
    menu_style = "slide-menu" # "open-menu" or "slide-menu"

    # Date format
    dateformat = "" # default "2 Jan 2006"
    # See the format reference https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference

    # path name excluded from documentation menu
    menu_exclusion = [
        "archives",
        "archive",
        "blog",
        "entry",
        "post",
        "posts",
        "chapter1",
        "chapter2",
        "chapter3",
        "getting-started",
        "sample"
    ]

# Global menu section
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Dashboard"
    url = "https://tatreports.directi.com/"
    weight = 2

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false
